# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type', models.CharField(choices=[('Monitor', 'Monitor'), ('Laptop', 'Laptop'), ('Switch', 'Switch'), ('cable', 'Cable'), ('Key-board', 'Key-board')], default='', max_length=100)),
                ('Manufacture', models.CharField(choices=[('HP', 'HP'), ('Sisco', 'Sisco'), ('Dell', 'Dell')], default='', max_length=100)),
                ('Serial_no', models.CharField(default='', max_length=50)),
                ('Mac_ID', models.IntegerField(default='')),
                ('Assigned_to', models.CharField(choices=[('Employee', 'Employee'), ('Customer', 'Customer'), ('Technician', 'Technician'), ('Company', 'Company')], default='', max_length=100)),
                ('Technician', models.CharField(default='', max_length=100)),
                ('Purchase_date', models.CharField(default='', max_length=100)),
                ('Issue_date', models.CharField(default='', max_length=100)),
                ('Warntee', models.CharField(default='', max_length=100)),
                ('Maintainance', models.CharField(default='', max_length=100)),
                ('Location', models.CharField(default='', max_length=50)),
                ('Comments', models.TextField(default='', max_length=500)),
                ('Status', models.CharField(default='', max_length=100)),
                ('Duration', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
