# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20170912_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type', models.CharField(choices=[('Monitor', 'Monitor'), ('Laptop', 'Laptop'), ('Switch', 'Switch'), ('cable', 'Cable'), ('Key-board', 'Key-board')], default='', max_length=100)),
                ('Manufacture', models.CharField(choices=[('HP', 'HP'), ('Sisco', 'Sisco'), ('Dell', 'Dell')], default='', max_length=100)),
                ('Serial_no', models.CharField(default='', max_length=50)),
                ('Mac_ID', models.IntegerField(default='')),
                ('Technician', models.CharField(default='', max_length=100)),
                ('Assigned_to', models.CharField(choices=[('Employee', 'Employee'), ('Customer', 'Customer'), ('Technician', 'Technician'), ('Company', 'Company')], default='', max_length=100)),
                ('Purchase_date', models.DateField(verbose_name='Date')),
                ('Warranty_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Location', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
