# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Assigned_to',
            new_name='Assigned_To',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Location',
            new_name='Locations',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Mac_ID',
            new_name='Mac_Id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Manufacture',
            new_name='Makes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Type',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Purchase_date',
            new_name='Purchase_Date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Serial_no',
            new_name='Serial_nu',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Technician',
            new_name='Technicians',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Warranty_time',
            new_name='Warranty_Time',
        ),
    ]
