# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20170914_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Purchase_Date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Warranty_Time',
            field=models.TextField(default=''),
        ),
    ]
