# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20170914_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_issue', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('comments', models.TextField(default='', max_length=300)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Product')),
            ],
        ),
    ]
