# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Location',
            field=models.CharField(choices=[('merit', 'merit'), ('lintel', 'lintel'), ('branch', 'branch')], default='', max_length=50),
        ),
    ]
